### ISSUE TITLE
Adding comments to functions

### ISSUE THREAD

**Issue by pordaniel01** [osrep/Runaphys#10]
We should discuss if we sould add more comments to the functions.

**Comment by gergopokol** [comment]
Public functions that can be directly called should be described in comments. Check if the function can be used based on name, parameters and comment on usage.
Comments for non-trivial lines can be added if unavoidable.
Readme file is to be updated with basic documentation. Example: https://github.com/ftsrg/theta

**Comment by pordaniel01** [comment]
Comments have been updated.
