### ISSUE TITLE
Fix test fail on Travis

### ISSUE THREAD

**Issue by olaszsoma** [osrep/Runaphys#18]
The [isFieldCritical test](https://github.com/osrep/Runaphys/blob/development/test/tests.cpp#L45) fails on Travis for some reason. The same test is successful on Gateway. The reason for this is unknown, but it should be fixed before release.

**Comment by olaszsoma** [comment]
The problem does not come from the loading of ITM_CONSTANTS environmental variable on Gateway. I have manually changed the loading on Gateway, and the test still succeeded there, while it fails on Travis.

**Comment by olaszsoma** [comment]
A new branch has been created for this issue. Commits will be made referencing this issue which will not be merged into development.

**Comment by olaszsoma** [comment]
Test does not compile.

**Comment by olaszsoma** [comment]
The abs function seems to be the problem on Travis. It returns 0 on the electric field.

**Comment by olaszsoma** [comment]
The absolute value function does not work on travis. Changing this to fabs, which works on floating-point numbers (but should do the same as abs) seems to solve the problem.

**Comment by olaszsoma** [comment]
Changing abs to std::abs also solves the problem. It might be better to use this.

**Comment by olaszsoma** [comment]
We will go for the std:: solution.

**Comment by olaszsoma** [comment]
All the abs functions have been fixed in Runaphys, this issue can be closed.

**Comment by olaszsoma** [comment]
This fix has to be implemented on a new branch.

**Comment by gergopokol** [comment]
Fixed.
