### ISSUE TITLE
Implement unit tests

### ISSUE THREAD

**Issue by gergopokol** [osrep/Runaphys#2]
Goole Test framework is to be used. Much of this can be moved here from Runin.

**Comment by gergopokol** [comment]
This actually works already. test_phys.cpp is to be renamed to test.cpp, and this can be closed.

**Comment by pordaniel01** [comment]
test_phys.cpp has been renamed tests.cpp.

**Comment by pordaniel01** [comment]
CMake has also been updated. Issue can be closed.
