### ISSUE TITLE
Importing hdf5 components from Runafluid

### ISSUE THREAD

**Issue by pordaniel01** [osrep/Runaphys#38]
hdf5 requires the H5Cpp.h header. It should be discussed how to import these package to Runaphys.

**Comment by gergopokol** [comment]
Existence of H5Cpp.h should be listed as a requirement. It seems to be available: https://support.hdfgroup.org/HDF5/doc1.6/cpplus_RM/H5Cpp_8h.html

**Comment by pordaniel01** [comment]
Building hdf5 takes more than 10 minutes. This significantly increases the whole build time, therefore we decided that travis will not build hdf5.
I will include a condition, that checks if hdf5 is on the target system, and if not, it will skip building steps for hdf5 components.

**Comment by pordaniel01** [comment]
The hdf5 components also uses blitz arrays. This was included in UALClasses.h which is unavailable outside of Gateway. 
I will try to replace the blitz arrays with standard arrays. If this fails, we might try to include the blitz includes instead of UALClasses so it can work on systems with blitz installed.

**Comment by pordaniel01** [comment]
It seems that the blitz arrays are used without any reason, and can be replaced with general arrays. 
Also it seems like implementing blitz arrays just added an extra step that can be skipped.
We are further investingating this with @matyasaradi and @olaszsoma .
