### ISSUE TITLE
Writing new tests for Runaphys

### ISSUE THREAD

**Issue by pordaniel01** [osrep/Runaphys#39]
runafluid_control function has been imported from Runafluid, however there are no tests that cover any of its functionalities. This drastically lowers the coverage of Runaphys therefore new testcases should be written for this function.

**Comment by pordaniel01** [comment]
We should also test the error messages of runafluid_switch_message.

**Comment by gergopokol** [comment]
It should also be renamed to `advance_runaway_population`. 

`runafluid_switch_message` should also be renamed to `list_parameter_settings`.

**Comment by pordaniel01** [comment]
Here are some old bugs from [Runin](https://gforge6.eufus.eu/gf/project/runin/tracker/) and [Runafluid](https://gforge6.eufus.eu/gf/project/runafluid/tracker/)

**Comment by pordaniel01** [comment]
The new test that checks the `advance_runaway_population` function fails, if the error treshold is set below 10^-4.
