### ISSUE TITLE
Implement SonarCloud tests

### ISSUE THREAD

**Issue by gergopokol** [osrep/Runaphys#4]
Much of this can be imported from Runin.

**Comment by pordaniel01** [comment]
I added a new encryption key to the repository. The key can be found on the deep server at:
/pordani/runaphys_key

**Comment by gergopokol** [comment]
Repositpry access granted at https://github.com/organizations/osrep/settings/installations/9497318

**Comment by pordaniel01** [comment]
Basic Sonarscan has been set up .Code coverage report will be added. See issue [#8 ](https://github.com/osrep/Runaphys/issues/8)
