### ISSUE TITLE
Readme should be updated

### ISSUE THREAD

**Issue by pordaniel01** [osrep/Runaphys#40]
Runaphys is opensource and everyone should be able to use it. Therefore it needs a clear Read me file, that gives instructions to potential users how to utilize the contents of this repository. 
An [example](https://github.com/ftsrg/theta) was given by @micskeiz .

**Comment by gergopokol** [comment]
Earlier user docs can be used as a source of info: https://portal.eufus.eu/twiki/bin/view/Main/HCD-ElectronRun-awayPhysics
